project:
  type: website
  output-dir: _output

format:
  titlepage-pdf:
    template-partials:
      - partials/before-body.tex
      - partials/margin-header.tex
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: false
    toc: false
    include-in-header: 
      text: |
        \usepackage{xcolor}
        \definecolor{noaablue}{HTML}{003366}
        \definecolor{noaalightblue}{HTML}{336699}
        \usepackage{fancyhdr}
        \usepackage{graphicx}
        \usepackage{geometry}
    include-before-body:
      text: |
        \pagestyle{fancy}
        \fancyhf{}
        \renewcommand{\headrulewidth}{0pt}
        \fancyhead[R]{\includegraphics[width=1in]{assets/NOAA_FISHERIES_logoH_web.png}}
