project:
  type: website
  output-dir: _output
  preview:
    port: 4200
    browser: false
  render:
    - model_card_modern.qmd

metadata:
  lang: en
  mainfont: Helvetica
  sansfont: Helvetica
  monofont: "Courier New"
  papersize: letter
  geometry:
    - top=0.75in
    - bottom=0.75in
    - left=0.75in
    - right=0.75in
  fontsize: 10pt
  linkcolor: blue
  urlcolor: blue
  date: today
  author-meta: "NOAA Fisheries"

format:
  titlepage-pdf:
    documentclass: scrbook
    papersize: letter
    classoption: ["oneside", "open=any"]
    number-sections: false
    toc: false
    lof: false
    lot: false
    highlight-style: github
    template-partials:
      - partials/before-body.tex
      - partials/margin-header.tex
    pdf-engine: xelatex
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{xcolor}
        \definecolor{noaablue}{HTML}{003366}
        \definecolor{noaalightblue}{HTML}{336699}
        \definecolor{lightgray}{HTML}{F6F8FA}
        \usepackage{tcolorbox}
        \tcbuselibrary{skins}
        \usepackage{fancyhdr}
        \usepackage{graphicx}
        \usepackage{geometry}
