version: '3.8'

services:
  quarto:
    build:
      context: .
      dockerfile: Dockerfile
    image: quarto-pdf:latest
    volumes:
      - ./:/home/quarto/project:rw
    working_dir: /home/quarto/project
    command: >
      quarto render
      model_card_modern.qmd
      --to pdf
