version: "3"
services:
  model-card:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: /bin/bash -c "
      quarto render model_card_modern.qmd --to pdf
    "
