name: Generate Model Card PDF

on:
  push:
    branches:
      - main # Or your default branch like 'master'
    paths:
      - 'generate_model_card.py'
      - 'model_card_data.json'
      - 'requirements.txt'
      - '*.png' # Trigger if any image files are changed
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model card generator
      # The script now defaults to model_card_data.json, no need to pass paths
      run: python generate_model_card.py

    - name: Upload generated PDF
      uses: actions/upload-artifact@v4
      with:
        name: model-card-pdf
        path: model_card.pdf # The name of the PDF file generated by your script