name: Build Model Card via Python

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Model Card
      run: |
        python python/build.py
        
    - name: Upload Model Card PDF
      uses: actions/upload-artifact@v4
      with:
        name: model-card
        path: Model_Card.pdf
        if-no-files-found: error