name: Build Model Cards

on:
  push:
    branches: [main]
    paths:
      - '**.qmd'
      - '**.yml'
      - 'assets/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release
        
    - name: Install TinyTeX
      run: |
        quarto install tool tinytex
        quarto install extension quarto-journals/elsevier
        
    - name: Install Fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-liberation
        
    - name: Render Documents
      run: |
        quarto render model_card_modern.qmd --to pdf
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./_output/*.pdf
        name: "Model Card Update ${{ github.sha }}"
        tag_name: "v${{ github.run_number }}"
        body: "Automated model card update"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
