name: Model Card Builder

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  build_model_card:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'huggingface.co/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pyyaml reportlab

      - name: Extract Hugging Face URL
        id: extract-url
        run: |
          URL=$(echo "${{ github.event.issue.body }}" | grep -o 'https://huggingface.co/[^ ]*' | head -n1)
          REPO_ID=$(echo $URL | sed 's|https://huggingface.co/||')
          echo "repo_id=$REPO_ID" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Install gh-models extension
        run: |
          gh extension install https://github.com/github/gh-models || echo "Extension may already be installed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get model card content for summary
        id: get-model-card
        run: |
          curl -s "${{ steps.extract-url.outputs.url }}" > model_card.txt

      - name: Generate AI summary
        run: |
          if [ -f summarize_model.prompt.yaml ]; then
            cat model_card.txt | gh models run --file summarize_model.prompt.yaml > summary.txt
          else
            echo "summarize_model.prompt.yaml not found, skipping summary generation" > summary.txt
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare directories
        run: |
          mkdir -p assets

      - name: Fetch Hugging Face model card
        run: |
          python fetch_hf_model_card.py "${{ steps.extract-url.outputs.repo_id }}"

      - name: Build PDF from model card
        run: |
          python build.py --output Model_Card.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: Model_Card.pdf

      - name: Comment on issue with summary and download instructions
        run: |
          SUMMARY=$(cat summary.txt)
          gh issue comment ${{ github.event.issue.number }} --body "### 📄 AI-Generated Model Card Summary

          ${SUMMARY}

          ---

          ✨ **A detailed PDF version of the model card has been generated and uploaded as an artifact.**

          📥 **To download the PDF**:
          1. Go to the **Actions** tab
          2. Click on the workflow run
          3. Scroll down to **Artifacts**
          4. Download **model-card-pdf**
          "
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
