name: Model Card Builder

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write
  contents: read

jobs:
  build_model_card:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'huggingface.co/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pyyaml reportlab

      - name: Extract Hugging Face URL
        id: extract-url
        run: |
          URL=$(echo "${{ github.event.issue.body }}" | grep -o 'https://huggingface.co/[^ ]*' | head -n1)
          REPO_ID=$(echo "$URL" | sed 's|https://huggingface.co/||')
          echo "repo_id=$REPO_ID" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Install gh-models extension
        run: |
          gh extension install https://github.com/github/gh-models || echo "Extension may already be installed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Hugging Face model card content
        id: fetch-model-card
        run: |
          curl -s "${{ steps.extract-url.outputs.url }}" > model_card.txt

      - name: Generate summary using GitHub Models
        run: |
          if [ -f summarize.prompt.yaml ]; then
            gh models run summarize < model_card.txt > summary.txt
          else
            echo "summarize.prompt.yaml not found. Skipping summary generation." > summary.txt
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare assets directory
        run: |
          mkdir -p assets

      - name: Fetch detailed Hugging Face model card (optional)
        run: |
          if [ -f fetch_hf_model_card.py ]; then
            python fetch_hf_model_card.py "${{ steps.extract-url.outputs.repo_id }}"
          else
            echo "fetch_hf_model_card.py not found. Skipping detailed fetch."
          fi

      - name: Build PDF from model card
        run: |
          if [ -f build.py ]; then
            python build.py --output Model_Card.pdf
          else
            echo "build.py not found. Skipping PDF generation."
          fi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: Model_Card.pdf

      - name: Comment on issue with summary
        run: |
          SUMMARY=$(cat summary.txt)
          gh issue comment ${{ github.event.issue.number }} --body "### 📄 AI-Generated Model Card Summary

          ${SUMMARY}

          ---

          ✨ **A detailed PDF version of the model card has been generated and uploaded as an artifact.**

          📥 **To download the PDF**:
          1. Go to the **Actions** tab
          2. Click on the workflow run
          3. Scroll down to **Artifacts**
          4. Download **model-card-pdf**
          "
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
