name: Build and Publish Model Cards

# Add status badge to README:
# [![Build Status](https://github.com/noaa-fisheries/model-card-template/actions/workflows/quarto-publish.yml/badge.svg)](https://github.com/noaa-fisheries/model-card-template/actions)

on:
  push:
    branches: [main]
    paths:
      - '**.qmd'
      - '**.yml'
      - 'assets/**'
      - 'partials/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install Dependencies
        run: |
          quarto install tool tinytex
          quarto install extension quarto-journals/elsevier
          sudo apt-get update
          sudo apt-get install -y fonts-liberation
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _output
