name: Build and Publish Model Cards

on:
  push:
    branches: [main]
    paths:
      - '**.qmd'
      - '**.yml'
      - 'assets/**'
      - 'partials/**'
      - 'scripts/**'
  workflow_dispatch:

env:
  TINYTEX_DIR: ~/.TinyTeX
  QUARTO_VERSION: pre-release

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/quarto-dev/quarto:latest
      env:
        DEBIAN_FRONTEND: noninteractive
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache TinyTeX
        uses: actions/cache@v4
        with:
          path: ~/.TinyTeX
          key: tinytex-${{ runner.os }}-${{ hashFiles('**/model_card_modern.qmd') }}
          restore-keys: |
            tinytex-${{ runner.os }}-

      - name: Install minimal TeX dependencies
        run: |
          # Only install if cache miss
          if [ ! -d ~/.TinyTeX ]; then
            echo "Installing TinyTeX..."
            quarto install tool tinytex --no-prompt
            
            # Add TinyTeX to PATH
            export PATH="$HOME/.TinyTeX/bin/x86_64-linux:$PATH"
            
            # Update tlmgr
            tlmgr update --self
            
            # Install only required packages
            tlmgr install \
              collection-basic \
              collection-latex \
              collection-fontsrecommended \
              collection-latexrecommended \
              geometry \
              fancyhdr \
              xcolor \
              tcolorbox \
              fontspec
          fi
          
          # Always install extensions
          quarto install extension quarto-journals/elsevier --no-prompt      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            fonts-liberation \
            make \
            git \
            perl \
            perl-modules \
            cpanminus
          
          # Install required Perl modules
          cpanm --no-wget File::Find

      - name: Verify TinyTeX installation
        run: |
          echo "Verifying TinyTeX installation..."
          export PATH="$TINYTEX_DIR/bin/x86_64-linux:$PATH"
          
          # Check TinyTeX
          if ! command -v tlmgr &> /dev/null; then
              echo "Error: tlmgr not found. TinyTeX installation failed."
              exit 1
          fi
          tlmgr --version
          
          # Check required packages
          for pkg in "geometry.sty" "fancyhdr.sty" "xcolor.sty" "tcolorbox.sty"; do
            if ! kpsewhich "$pkg" &> /dev/null; then
              echo "Error: $pkg not found. Package installation may have failed."
              exit 1
            fi
            echo "✓ Found $pkg"
          done

      - name: Render Model Card
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf

      - name: Verify PDF Generation
        run: |
          if [ ! -f "_output/model_card_modern.pdf" ]; then
            echo "Error: PDF was not generated"
            exit 1
          fi
          echo "PDF generated successfully"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
          if-no-files-found: error

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _output
          clean: true
