name: Build and Publish Model Cards

on:
  push:
    branches: [main]
    paths:
      - '**.qmd'
      - '**.yml'
      - 'assets/**'
      - 'partials/**'
      - 'scripts/**'
  workflow_dispatch:

env:
  TINYTEX_DIR: ~/.TinyTeX
  QUARTO_VERSION: pre-release

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and render
        run: |
          docker-compose build
          docker-compose run --rm model-card

      - name: Verify PDF Generation
        run: |
          if [ ! -f "_output/model_card_modern.pdf" ]; then
            echo "Error: PDF was not generated"
            exit 1
          fi
          echo "PDF generated successfully"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
          if-no-files-found: error

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _output
          clean: true
