# .github/workflows/render-pdf.yml
name: Render Model Card PDF

on:
  push:
    branches: [ main ]

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto CLI & TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 'latest'
          tinytex: true       # ← installs TinyTeX via `quarto install tool tinytex`

      - name: Render PDF
        run: |
          quarto render model_card_modern.qmd --to pdf

      - name: List generated PDF
        run: ls -lah _output

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-card-pdf
          path: _output/*.pdf
