name: Build PDF via Docker

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # A) Get your code
      - uses: actions/checkout@v3

      # B) Enable Docker Buildx for cache
      - uses: docker/setup-buildx-action@v3

      # C) Restore layer cache
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # D) Build your Quarto/TinyTeX image
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: quarto-pdf:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to:   type=local,dest=/tmp/.buildx-cache

      # E) Run the container to generate PDF
      - name: Render model card PDF
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/quarto/project \
            quarto-pdf:latest

      # F) Publish the PDF as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: model-card-pdf
          path: _output/*.pdf
