# .github/workflows/render-pdf.yml
name: Render PDF with Quarto CLI

on:
  push:
    branches: [ main ]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-actions/setup-quarto@v2

      - name: Install TeX Live (APT)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra \
            fonts-liberation

      - name: Render PDF
        run: quarto render model_card_modern.qmd --to pdf

      - name: List output
        run: ls -lh _output/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-card-pdf
          path: _output/*.pdf
