name: Build and Publish Model Cards

# Add status badge to README:
# [![Build Status](https://github.com/noaa-fisheries/model-card-template/actions/workflows/quarto-publish.yml/badge.svg)](https://github.com/noaa-fisheries/model-card-template/actions)

on:
  push:
    branches: [main]
    paths:
      - '**.qmd'
      - '**.yml'
      - 'assets/**'
      - 'partials/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/quarto-dev/quarto:latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache TinyTeX
        uses: actions/cache@v4
        with:
          path: ~/.TinyTeX
          key: tinytex-${{ runner.os }}-${{ hashFiles('**/model_card_modern.qmd') }}
          restore-keys: |
            tinytex-${{ runner.os }}-      - name: Install minimal TeX dependencies
        run: |
          # Only install if cache miss
          if [ ! -d ~/.TinyTeX ]; then
            echo "Installing TinyTeX..."
            quarto install tool tinytex --no-prompt
            
            # Add TinyTeX to PATH
            export PATH="$HOME/.TinyTeX/bin/x86_64-linux:$PATH"
            
            # Update tlmgr
            tlmgr update --self
            
            # Install only required packages
            tlmgr install \
              collection-basic \
              collection-latex \
              collection-fontsrecommended \
              collection-latexrecommended \
              geometry \
              fancyhdr \
              xcolor \
              tcolorbox \
              fontspec
          fi
          
          # Always install extensions
          quarto install extension quarto-journals/elsevier --no-prompt

      - name: Install system fonts
        run: |
          apt-get update
          apt-get install -y --no-install-recommends fonts-liberation
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _output
