name: Quarto Model Card

on:
  workflow_dispatch:
  push:
    paths:
      - '**.qmd'
      - '.github/workflows/quarto-model-card.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt jupyter
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true
      - name: Render model card
        run: |
          quarto render model_card_template.qmd --output-dir _output
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-html
          path: _output/
