# .github/workflows/render-modelcard.yml
name: Build one-page Model Card PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) install Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      # 2) **fix:** install TeX Live (v3 tag!)
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3    # ← was @v2
        with:
          # enough for xelatex + common packages; tweak if you need more
          packages: |
            scheme-small
            xetex
            fontspec
            sectsty
            xcolor
            geometry

      # 3) render PDF only
      - run: quarto render example_model_card.qmd --to pdf

      # 4) upload artefact
      - uses: actions/upload-artifact@v4
        with:
          name: fish-detector-card
          path: example_model_card.pdf
