name: Build one-page model card PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      - name: Install TeX (tinytex)
        uses: teatimeguest/setup-texlive@v2       # light-weight TeXLive

      - name: Render PDF
        run: |
          quarto render example_model_card.qmd --to pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fish-detector-card
          path: example_model_card.pdf
