name: Build one-page Model Card PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.0"        # explicit tag avoids vlatest 404

      # TinyTeX only – no font downloads needed
      - name: Install TinyTeX
        run: |
          quarto install tinytex --no-prompt

      - name: Render model card
        run: |
          quarto render example_model_card.qmd --to pdf

      - uses: actions/upload-artifact@v4
        with:
          name: fish-detector-card
          path: example_model_card.pdf
