name: Build one-page Model Card PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1 ── Install Quarto CLI (pinned)
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.0"          # <── was "latest"

      # 2 ── TinyTeX + font
      - name: Install TinyTeX & fonts
        run: |
          quarto install tinytex --no-prompt
          sudo apt-get update
          sudo apt-get install -y fonts-source-sans-pro

      # 3 ── Render PDF
      - name: Render model card
        run: |
          quarto render example_model_card.qmd --to pdf

      # 4 ── Upload artefact
      - uses: actions/upload-artifact@v4
        with:
          name: fish-detector-card
          path: example_model_card.pdf
